#!/usr/bin/env python3
"""Generate src/+netra/+util/i18n.m from strings.tsv.

The MATLAB file stores non-English text as Unicode code points so that the
source stays pure ASCII and decodes identically in every MATLAB locale and in
GNU Octave (where char is UTF-8 bytes). Edit strings.tsv, then run:

    python3 tools/i18n/gen_i18n.py
"""
import csv
import pathlib

here = pathlib.Path(__file__).resolve().parent
rows = list(csv.DictReader(open(here / "strings.tsv", encoding="utf-8"), delimiter="\t"))
langs = [c for c in rows[0].keys() if c not in ("key",)]


def mstr(s):
    return "'" + s.replace("'", "''") + "'"


def cps(s):
    out, line = [], []
    for ch in s:
        line.append(str(ord(ch)))
    # wrap long arrays for readability
    chunks = [" ".join(line[i:i + 24]) for i in range(0, len(line), 24)]
    return "[" + " ...\n            ".join(chunks) + "]"


body = []
for r in rows:
    vals = []
    for lang in langs:
        if lang == "en":
            vals.append(mstr(r[lang]))
        else:
            vals.append(cps(r[lang]))
    body.append("    " + mstr(r["key"]) + ", ...\n        " + ", ...\n        ".join(vals))

lang_list = ", ".join(mstr(l) for l in langs)
src = f"""function txt = i18n(key, lang)
%I18N Patient- and technician-facing text ({", ".join(langs)}).
%   txt = netra.util.i18n(key, lang) with lang = {lang_list}.
%   Keys: triage.<ROUTINE|REFER|URGENT|HUMAN_REVIEW|RECAPTURE>, dme,
%   fb.<blur|dark|bright|field|contrast|artifact|anatomy>, grade.<0..4>.
%
%   GENERATED by tools/i18n/gen_i18n.py from tools/i18n/strings.tsv - edit
%   the TSV (UTF-8) and regenerate; do not edit this file by hand.
%   Non-English text is stored as Unicode code points so this file is pure
%   ASCII and decodes the same in every MATLAB locale and in GNU Octave.
if nargin < 2
    lang = 'en';
end
langs = {{{lang_list}}};
col = find(strcmpi(langs, lang), 1);
if isempty(col)
    error('netra:i18n:lang', 'Unsupported language "%s".', lang);
end
persistent T
if isempty(T)
    rows = {{
{(";" + chr(10)).join(body)}
    }};
    T = containers.Map();
    for k = 1:size(rows, 1)
        entry = cell(1, numel(langs));
        for j = 1:numel(langs)
            v = rows{{k, j + 1}};
            if ischar(v)
                entry{{j}} = v;
            else
                entry{{j}} = decode(v);
            end
        end
        T(rows{{k, 1}}) = entry;
    end
end
if ~isKey(T, key)
    error('netra:i18n:key', 'No text for key "%s".', key);
end
entry = T(key);
txt = entry{{col}};
end

function s = decode(cp)
% MATLAB char is UTF-16; Octave char is UTF-8 bytes.
if exist('OCTAVE_VERSION', 'builtin') > 0
    b = zeros(1, 4 * numel(cp));
    n = 0;
    for c = cp
        if c < 128
            e = c;
        elseif c < 2048
            e = [192 + floor(c / 64), 128 + mod(c, 64)];
        elseif c < 65536
            e = [224 + floor(c / 4096), 128 + mod(floor(c / 64), 64), 128 + mod(c, 64)];
        else
            e = [240 + floor(c / 262144), 128 + mod(floor(c / 4096), 64), ...
                 128 + mod(floor(c / 64), 64), 128 + mod(c, 64)];
        end
        b(n + 1:n + numel(e)) = e;
        n = n + numel(e);
    end
    s = char(b(1:n));
else
    s = char(cp);
end
end
"""
out = here.parent.parent / "src" / "+netra" / "+util" / "i18n.m"
out.write_text(src, encoding="ascii")
print(f"wrote {out} ({len(rows)} keys, languages: {', '.join(langs)})")
